@startuml


TourPlaner -> AddTourView : addTour()
AddTourView -> AddTourViewModel : addTour()
AddTourViewModel -> TourService: save()
TourService-> TourRepository : save()
TourRepository -> TourService: returnAllTours()
TourRepository -> TourRepository : publishEvent(NewTour)

TourListViewModel -> TourListViewModel : eventAggregator(onNewTour)
TourListViewModel -> TourService : onNewTour()
TourService-> TourRepository: findAll()
TourRepository -> TourRepository : findAll()
TourRepository --> TourService
TourService --> TourListViewModel
TourListViewModel --> TourListView
TourListView --> TourPlaner

@enduml